from fuzzywuzzy import fuzz
from fuzzywuzzy import process
async def autocorrect(mob):
  query = mob
  correction = {
    "fqueen": "queen fire ant",
    "queenf": "queen fire ant",
    "fqa": "queen fire ant",
    "fq": "queen fire ant",
    "hel": "hel beetle",
    "hell": "hel beetle",
    "hb": "hel beetle",
    "hbe": "hel beetle",
    "hellb": "hel beetle",
    "hbeetle": "hel beetle",
    "ss": "sandstorm",
    "helly": "jellyfish",
    "ovm": "termite overmind",
    "hrl": "hel beetle",
    "hwl": "hel beetle",
    "fireant": "queen fire ant",
    "qfa": "queen fire ant",
    "jely": "jellyfish",
    "shel": "shell",
    "firquen": "queen fire ant",
    "quen": "queen ant",
    "overmimd": "termite overmind",
    "fqeen": "queen fire ant",
    "sandstorm": "sandstorm",
    "dcenti": "desert centipede",
    "dcent": "desert centipede",
    "dc": "desert centipede",
    "hormet": "hornet",
    "queef": "queen fire ant", 
    "ecenti":"evil centipede",
    "queen fire":"queen fire ant",
    "hellbeetle":"hel beetle",
    "qf":"queen fire ant",
    "deceti":"desert centipede",
    "sfq":"queen fire ant",
    "stra":"starfish",
    "ff":"firefly",
    "ffly":"firefly",
    "ae":"ant egg",
    "ah":"ant hole",
    "ba":"baby ant",
    "bfa":"baby fire ant",
    "fba":"baby fire ant",
    "bt":"baby termite",
    "bterm":"baby termite",
    "b":"bee",
    "bb":"bumble bee",
    "dlady":"dark ladybug",
    "ecenti":"evil centipede",
    "fab":"fire ant burrow",
    "fah":"fire ant burrow",
    "fire and hole":"fire and burrow",
    "fae":"fire ant egg",
    "fantegg":"fire ant egg",
    "slady":"shiny ladybug",
    "sa":"soldier ant",
    "sfa":"soldier fire ant",
    "fsa":"soldier fire ant",
    "st":"soldier termite",
    "sterm":"soldier termite",
    "wa":"worker ant",
    "wfa":"worker fire ant",
    "fwa":"worker fire ant",
    "wt":"worker termite",
    "fbaby":"fire baby ant",
    "lady":"ladybug"
  }
  for i in correction:
    if i == mob:
      return(correction[i])
  else:
    choices = ['ant egg', 'ant hole', 'evil centipede', 'baby ant', 'baby fire ant', 'bumble bee', 'baby termite', 'bumble bee', 'dark ladybug', 'digger', 'fire ant burrow', 'fire ant egg', 'shiny ladybug', 'soldier ant', 'soldier fire ant', 'soldier termite', 'sponge', 'square', 'target dummy', 'termite egg', 'termite mound', 'worker ant', 'worker fire ant', 'worker termite', 'crab', 'termite overmind', 'bee', 'beetle', 'wasp','cactus', 'centipede', 'dandelion', 'firefly', 'fly','hornet', 'hel beetle', 'jellyfish', 'ladybug', 'leech', 'queen ant','queen fire ant', 'moth', 'rock', 'sandstorm', 'spider', 'cockroach', 'shell', 'bubble', 'desert centipede', 'leafbug', 'mantis', 'bush', 'scorpion','starfish']
    return(process.extractOne(query, choices)[0])
